# Generated by Django 5.1 on 2024-09-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=255)),
                ('image', models.URLField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('ratings', models.FloatField()),
                ('ingredients', models.TextField()),
                ('steps', models.TextField()),
                ('nutrients', models.JSONField()),
                ('times', models.JSONField()),
                ('serves', models.IntegerField()),
                ('difficult', models.CharField(max_length=50)),
                ('vote_count', models.IntegerField()),
                ('subcategory', models.CharField(max_length=100)),
                ('dish_type', models.CharField(max_length=100)),
                ('maincategory', models.CharField(max_length=50)),
            ],
        ),
    ]
